#ADM_CYCLER_INFO
required_data(c("STG_CYCLER_TYPE", "STG_CYCLER", "STG_TEAM"))


ADM_CYCLER_INFO <- STG_CYCLER_TYPE[STG_CYCLER, on = "CYCLER_TYPE_ID"][STG_TEAM, on = "TEAM_ID"]
ADM_CYCLER_INFO[, UI_text := paste0(TEAM_COLOR, "-", CYCLER_TYPE_NAME)]
ADM_CYCLER_INFO[, SHORT_TYPE := str_sub(CYCLER_TYPE_NAME, 1, 1)]
ADM_CYCLER_INFO[, UI_COLOR := tolower(TEAM_COLOR)]
