tabItem(tabName = "tab_input_other_moves",
        fluidPage(column(3,uiOutput("radioGroups")),
                  column(9,
                  fluidRow(actionButton(inputId = "played_E",
                                        label = "E",
                                        width = "33%",
                                        style='height:200px; font-size:400%'),
                           actionButton(inputId = "played_2",
                                        label = "2",
                                        width = "33%",
                                        style='height:200px; font-size:400%'),
                           actionButton(inputId = "played_3",
                                        label = "3",
                                        width = "33%",
                                        style='height:200px; font-size:400%')),
                  fluidRow(
                    actionButton(inputId = "played_4",
                                 label = "4",
                                 width = "33%",
                                 style='height:200px; font-size:400%'),
                    actionButton(inputId = "played_5",
                                 label = "5",
                                 width = "33%",
                                 style='height:200px; font-size:400%'),
                    actionButton(inputId = "played_6",
                                 label = "6",
                                 width = "33%",
                                 style = 'height:200px; font-size:400%')),
                  fluidRow(
                    actionButton(inputId = "played_7",
                                 label = "7",
                                 width = "33%",
                                 style = 'height:200px; font-size:400%'),
                    actionButton(inputId = "played_9",
                                 label = "9",
                                 width = "33%",
                                 style = 'height:200px; font-size:400%'),
                    actionButton(inputId = "undo_played",
                                 label = "Undo",
                                 width = "33%",
                                 style = 'height:200px; font-size:400%')),
                  fluidRow(column(4,
                                  h3(htmlOutput("cards_playedt"))),
                           column(8,
                                  actionButton(inputId = "save_played_cards",
                                               label = "Confirm played cards",
                                               width = "100%",
                                               style = 'height:200px; font-size:200%',
                                               onclick = "Shiny.onInputChange('startThis',true)")))


        )
        )

)
